### ISSUE TITLE
updating a Recovery partition possible?

### ISSUE THREAD

**Issue by pexner** [MagerValp/Create-Recovery-Partition-Installer#3]
Hi,
Your README says "...it'll create an installer package that CREATES Recovery partitions.".
Is it possible to UPDATE an existing Recovery partition using a .pkg created with "Create-Recovery-Partition-Installer"?

Thanks in advance,
pe

**Comment by MagerValp** [comment]
Yes, it overwrites any existing recovery partitions. I clarified the readme, thanks.
