### ISSUE TITLE
10.11?

### ISSUE THREAD

**Issue by kcrawford** [MagerValp/Create-Recovery-Partition-Installer#4]
This is very handy.  Thanks for creating it.

I just tried it once with 10.11 GM and did not work.  Think it can be made to work?

I did run it while booted from a 10.10 machine.

Error was:
Error (async): The provided disk image is not a bootable OS X system volume (-69735)

**Comment by MagerValp** [comment]
I haven't tried creating recovery partitions that aren't of the same version as the host OS. I don't think Apple's tools support that.
