### ISSUE TITLE
Which Version will be installed?

### ISSUE THREAD

**Issue by tristan-k** [MagerValp/Create-Recovery-Partition-Installer#5]
[Line 71](https://github.com/MagerValp/Create-Recovery-Partition-Installer/blob/master/Create%20Recovery%20Partition%20Installer.app/Contents/Resources/script#L71) of the script shows that [RecoveryHDUpdate.dmg](http://support.apple.com/downloads/DL1464/en_US/RecoveryHDUpdate.dmg) will be downloaded from apple.com. This seems to be the [Lion Recovery Update v1.0](https://support.apple.com/kb/DL1464?locale=en_US) posted on the `Oct 12, 2011`. So if I run the installer on a more recent version of Mac OS, for example El Capitan, I then will only get a copy of the ancient Mac OS X Lion Recovery? Or how does the process work?

**Comment by MagerValp** [comment]
It'll install the recovery version from the installer app that you provide. It downloads RecoveryHDUpdate.dmg only to extract the `dmtest` binary needed for the package.
