### ISSUE TITLE
cocoaDialog download fails

### ISSUE THREAD

**Issue by jcosper** [MagerValp/Create-Recovery-Partition-Installer#6]

**Comment by macguitarman** [comment]
Love this app, but current version looks broken on 10.12.4

/private/var/folders/ls/ny_wgky942xcrw4bl7tpjgj00000gk/T/AppTranslocation/9CD21EBD-5A87-49A6-B4C7-E96DC1565A19/d/Create Recovery Partition Installer.app/Contents/Resources/script: line 39: ./cocoaDialog.app/Contents/MacOS/cocoaDialog: No such file or directory
Cancelled!

**Comment by macguitarman** [comment]
For some reason CocoaDialog does not download, so you go download it, and drag it to /Contents/Resources. Got it to save a PKG, testing the actual install now...

**Comment by macguitarman** [comment]
This is broken on 10.12x, can you give some insight as to why, more than happy to assist....

**Comment by MagerValp** [comment]
I just downloaded it and ran it on 10.12.4 and it generated a working installer, so I'm not sure why the cocoaDialog download fails for you.

**Comment by macguitarman** [comment]
Thx, it’s working, both app and installer have to be in same location, desktop, not separate volumes

John
